# Generated by Django 4.2.1 on 2023-11-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='description',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='works',
            name='img_path',
            field=models.CharField(max_length=1000),
        ),
    ]
