# Generated by Django 4.2.1 on 2023-12-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_works_description_alter_works_img_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='works',
            name='tags',
            field=models.ManyToManyField(to='portfolio.tag'),
        ),
    ]
